title: <p align="center"> Ramkumar Pandurangan</p>
logo: assets/img/50767540.jpeg



description:
  <p align="center">
  <a href="linkedin.com/in/ramkumar-pandurangan-70799668">LinkedIn</a> |
  <a href="https://github.com/ramkumarpandurangan">GitHub</a>
 
  <br>  
  I'm working as a Test Automation Consultant in TOP MNC.
  Also Enthusiastic about Data Science Ecosystem especially Generative AI
  I am #GenerativeAIAspire
  Enthusiastic to Open source Contribution
  <br>
  </p>



theme: jekyll-theme-minimal
